services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - ${HOST_MUSIC_DIR}:${MUSIC_DIR}:ro

    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Either rely on DATABASE_URL or your config/database.yml reading these:
      DATABASE_URL: ${DATABASE_URL}
      MUSIC_DIR: ${MUSIC_DIR}
      # Or, if you prefer discrete vars in database.yml:
      # PGHOST: db
      # PGUSER: ${POSTGRES_USER}
      # PGPASSWORD: ${POSTGRES_PASSWORD}
      # PGDATABASE: ${POSTGRES_DB}